name: Send Release Webhook

on:
  release:
    types: [published]

  workflow_dispatch:  # מאפשר הפעלה ידנית

jobs:
  send_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install bs4 requests pyluach

      - name: Run webhook script
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
          RELEASE_URL: ${{ github.event.release.html_url }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN_YEMOT: ${{ secrets.TOKEN_YEMOT }}
        run: python webhooks/main.py
